version: 2

jobs:
  my_first_job:
    docker:
      - image: circleci/node:9.8.0-stretch-browsers
    steps:
      - checkout
      - run: echo "first job"
  my_second_job:
    docker:
      - image: circleci/node:9.8.0-stretch-browsers
    steps:
      - checkout
      - run: echo "second job"

workflows:
  version: 2
  build:
    jobs:
      - my_first_job
      - my_second_job:
          requires:
            - my_first_job
